
#include <appetizer.h>
#include <auto_generated.h>

#if defined(_WINDOWS)
#include <string>
#include <sstream>
#include <vector>
#include <windows.h>
#endif

#include "../main_ext/main_ext.h"
#include "../assets/scripts/my_project.h"


using namespace appetizer;


#if !defined(_EDITOR)
extern bool linkFuntreeGenerated ();
static void* ___dummy_link_funtree_generated = (void*)&linkFuntreeGenerated;
#endif


int main(int argc, char **argv) {

  // init
  auto ext_inited = onInit();
  unlikely (ext_inited == false)
    return -1;

  AutoGenerated::init();

  auto prj = new MyProject();
  if (App::init(argc, argv, prj) == false)
    return -1;


  // start
#if defined(USE_WEB_GPU)
  App::init_callback_angel().on_success(
      []() {
        App::start(onUpdate, onShutdown);
      }
  );
  App::init_callback_angel().step();
#else
  App::start(onUpdate, onShutdown);
#endif


  return 0;
}


#if defined(_WINDOWS)
int APIENTRY WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow) {

  /// parse args
  std::vector<std::string> args;
  {
    std::istringstream iss(lpCmdLine);
    std::string token;
    while (std::getline(iss, token, ' ')) {
        if (!token.empty()) {
            args.push_back(token);
        }
    }
  }

  int argc = args.size();
  char** argv = new char*[argc];
  for (int ai=0; ai<argc; ++ai)
    argv[ai] = no_const(args[ai].c_str());



  /// call main
  auto result = main(argc, argv);
  


  /// clean up
  delete[] argv;
  return result;
}
#endif
